from .reference_exceptions import (
    NoDatabookFoundError,
    ReferenceConfigGenerationError,
    ReferenceLinkGenerationError,
    CustomReferenceInitializationError,
    EmptyReferenceContentError,
    EmptyReferenceConfigError,
    InvalidReferenceContentTypeError,
    InvalidReferenceConfigTypeError,
    NO_DATABOOK_FOUND_MSG,
    REFERENCE_CONFIG_GEN_ERROR_MSG,
    COMPONENT_REFERENCE_CONFIG_ERROR_MSG,
    COMPONENT_REFERENCE_LINK_ERROR_MSG,
    CUSTOM_REFERENCE_INIT_ERROR_MSG,
    EMPTY_REFERENCE_CONTENT_ERROR_MSG,
    EMPTY_REFERENCE_CONFIG_ERROR_MSG,
    INVALID_REFERENCE_CONTENT_TYPE_MSG,
    INVALID_REFERENCE_CONFIG_TYPE_MSG
)

from .utils_exceptions import (
    LoaderError,
    FileNotFoundError,
    InvalidFileFormatError,
    LoadingYmlError,
    LoadingReferenceError,
    ListingReferenceError,
    InvalidFolderPathError,
    LOADER_ERROR_MSG,
    FILE_NOT_FOUND_ERROR_MSG,
    INVALID_FILE_FORMAT_ERROR_MSG,
    LOADING_YML_ERROR_MSG,
    LOADING_REFERENCE_ERROR_MSG,
    LISTING_REFERENCE_ERROR_MSG,
    INVALID_FOLDER_PATH_ERROR_MSG
)

from .tool_exceptions import (
    ToolError,
    ToolBuildingError,
    ToolExecutionError,
    MCPToolBuildingError,
    FunctionRetrievalError,
    FunctionLoadingError,
    ToolRegistrationError,
    ToolNotFoundError,
    MoziToolBuildingError,
    FunctionToolBuildingError,
    MOZI_TOOL_BUILDING_ERROR_MSG,
    TOOL_BUILDING_ERROR_MSG,
    TOOL_EXECUTION_ERROR_MSG,
    MCP_TOOL_BUILDING_ERROR_MSG,
    FUNCTION_RETRIEVAL_ERROR_MSG,
    FUNCTION_LOADING_ERROR_MSG,
    TOOL_REGISTRATION_ERROR_MSG,
    TOOL_NOT_FOUND_ERROR_MSG,
    FUNCTION_TOOL_BUILDING_ERROR_MSG,
)

from .mcp_exceptions import (
    MCPError,
    MCPInitializationError,
    MCPExecutionError,
    MCPUpdateError,
    MCPNotFoundError,
    MCPInvalidConfigError,
    MCPRegistrationError,
    MCP_INITIALIZATION_ERROR_MSG,
    MCP_EXECUTION_ERROR_MSG,
    MCP_UPDATE_ERROR_MSG,
    MCP_NOT_FOUND_ERROR_MSG,
    MCP_INVALID_CONFIG_ERROR_MSG,
    MCP_REGISTRATION_ERROR_MSG
)

from .resource_exceptions import (
    ResourceError,
    ModelSourceBuildError,
    ComponentModelSourceBuildError,
    HubInitializationError,
    ThermoDBRegistrationError,
    ComponentThermoDBBuildError,
    FunctionDispatcherError,
    ToolBuilderError,
    HubThermoHubBuildError,
    HubThermoHubCleanError,
    HubComponentReferenceConfigError,
    HubComponentReferenceRuleError,
    HubComponentThermoDBRegistrationError,
    HubComponentsThermoDBRegistrationError,
    HubComponentModelSourceBuildError,
    HubComponentsModelSourceBuildError,
    MODEL_SOURCE_BUILD_ERROR_MSG,
    COMPONENT_MODEL_SOURCE_BUILD_ERROR_MSG,
    HUB_INITIALIZATION_ERROR_MSG,
    THERMODB_REGISTRATION_ERROR_MSG,
    COMPONENT_THERMODB_BUILD_ERROR_MSG,
    FUNCTION_DISPATCHER_ERROR_MSG,
    TOOL_BUILDER_ERROR_MSG,
    HUB_THERMO_HUB_BUILD_ERROR_MSG,
    HUB_THERMO_HUB_CLEAN_ERROR_MSG,
    HUB_COMPONENT_REFERENCE_CONFIG_ERROR_MSG,
    HUB_COMPONENT_REFERENCE_RULE_ERROR_MSG,
    HUB_COMPONENT_THERMODB_REGISTRATION_ERROR_MSG,
    HUB_COMPONENTS_THERMODB_REGISTRATION_ERROR_MSG,
    HUB_COMPONENT_MODEL_SOURCE_BUILD_ERROR_MSG,
    HUB_COMPONENTS_MODEL_SOURCE_BUILD_ERROR_MSG
)

from .api_exceptions import (
    APIError,
    APICreationError,
    InvalidMCPTypeError,
    InvalidMCPListItemError,
    MCPAdditionError,
    API_CREATION_ERROR_MSG,
    INVALID_MCP_TYPE_ERROR_MSG,
    INVALID_MCP_LIST_ITEM_ERROR_MSG,
    MCP_ADDITION_ERROR_MSG
)

from .ptf_exceptions import (
    PTFError,
    PTFCalculationError,
    PTFInitializationError,
    PTFModelSourceError,
    PTFComponentError,
    PTFFeedSpecificationError,
    PTFSolverError,
    PTF_CALCULATION_ERROR_MSG,
    PTF_INITIALIZATION_ERROR_MSG,
    PTF_MODEL_SOURCE_ERROR_MSG,
    PTF_COMPONENT_ERROR_MSG,
    PTF_FEED_SPECIFICATION_ERROR_MSG,
    PTF_SOLVER_ERROR_MSG
)

from .ptm_exceptions import (
    PTMError,
    PTMCalculationError,
    PTMInitializationError,
    PTMModelSourceError,
    PTMComponentError,
    PTMFeedSpecificationError,
    PTMSolverError,
    PTMReferenceError,
    PTMFugacityError,
    PTMRootsAnalysisError,
    PTM_CALCULATION_ERROR_MSG,
    PTM_INITIALIZATION_ERROR_MSG,
    PTM_MODEL_SOURCE_ERROR_MSG,
    PTM_COMPONENT_ERROR_MSG,
    PTM_FEED_SPECIFICATION_ERROR_MSG,
    PTM_SOLVER_ERROR_MSG,
    PTM_REFERENCE_ERROR_MSG,
    PTM_FUGACITY_ERROR_MSG,
    PTM_ROOTS_ANALYSIS_ERROR_MSG
)

__all__ = [
    # Reference exceptions
    "NoDatabookFoundError",
    "ReferenceConfigGenerationError",
    "ReferenceLinkGenerationError",
    "CustomReferenceInitializationError",
    "EmptyReferenceContentError",
    "EmptyReferenceConfigError",
    "InvalidReferenceContentTypeError",
    "InvalidReferenceConfigTypeError",
    "NO_DATABOOK_FOUND_MSG",
    "REFERENCE_CONFIG_GEN_ERROR_MSG",
    "COMPONENT_REFERENCE_CONFIG_ERROR_MSG",
    "COMPONENT_REFERENCE_LINK_ERROR_MSG",
    "CUSTOM_REFERENCE_INIT_ERROR_MSG",
    "EMPTY_REFERENCE_CONTENT_ERROR_MSG",
    "EMPTY_REFERENCE_CONFIG_ERROR_MSG",
    "INVALID_REFERENCE_CONTENT_TYPE_MSG",
    "INVALID_REFERENCE_CONFIG_TYPE_MSG",

    # Utils exceptions
    "LoaderError",
    "FileNotFoundError",
    "InvalidFileFormatError",
    "LoadingYmlError",
    "LoadingReferenceError",
    "ListingReferenceError",
    "InvalidFolderPathError",
    "LOADER_ERROR_MSG",
    "FILE_NOT_FOUND_ERROR_MSG",
    "INVALID_FILE_FORMAT_ERROR_MSG",
    "LOADING_YML_ERROR_MSG",
    "LOADING_REFERENCE_ERROR_MSG",
    "LISTING_REFERENCE_ERROR_MSG",
    "INVALID_FOLDER_PATH_ERROR_MSG",

    # Tool exceptions
    "ToolError",
    "ToolBuildingError",
    "ToolExecutionError",
    "MCPToolBuildingError",
    "FunctionRetrievalError",
    "FunctionLoadingError",
    "ToolRegistrationError",
    "ToolNotFoundError",
    "TOOL_BUILDING_ERROR_MSG",
    "TOOL_EXECUTION_ERROR_MSG",
    "MCP_TOOL_BUILDING_ERROR_MSG",
    "FUNCTION_RETRIEVAL_ERROR_MSG",
    "FUNCTION_LOADING_ERROR_MSG",
    "TOOL_REGISTRATION_ERROR_MSG",
    "TOOL_NOT_FOUND_ERROR_MSG",
    "MoziToolBuildingError",
    "FunctionToolBuildingError",
    "MOZI_TOOL_BUILDING_ERROR_MSG",
    "FUNCTION_TOOL_BUILDING_ERROR_MSG",

    # MCP exceptions
    "MCPError",
    "MCPInitializationError",
    "MCPExecutionError",
    "MCPUpdateError",
    "MCPNotFoundError",
    "MCPInvalidConfigError",
    "MCPRegistrationError",
    "MCP_INITIALIZATION_ERROR_MSG",
    "MCP_EXECUTION_ERROR_MSG",
    "MCP_UPDATE_ERROR_MSG",
    "MCP_NOT_FOUND_ERROR_MSG",
    "MCP_INVALID_CONFIG_ERROR_MSG",
    "MCP_REGISTRATION_ERROR_MSG",

    # Resource exceptions
    "ResourceError",
    "ModelSourceBuildError",
    "ComponentModelSourceBuildError",
    "HubInitializationError",
    "ThermoDBRegistrationError",
    "ComponentThermoDBBuildError",
    "FunctionDispatcherError",
    "ToolBuilderError",
    "MODEL_SOURCE_BUILD_ERROR_MSG",
    "COMPONENT_MODEL_SOURCE_BUILD_ERROR_MSG",
    "HUB_INITIALIZATION_ERROR_MSG",
    "THERMODB_REGISTRATION_ERROR_MSG",
    "COMPONENT_THERMODB_BUILD_ERROR_MSG",
    "FUNCTION_DISPATCHER_ERROR_MSG",
    "TOOL_BUILDER_ERROR_MSG",

    # Hub-specific error messages
    "HUB_THERMO_HUB_BUILD_ERROR_MSG",
    "HUB_THERMO_HUB_CLEAN_ERROR_MSG",
    "HUB_COMPONENT_REFERENCE_CONFIG_ERROR_MSG",
    "HUB_COMPONENT_REFERENCE_RULE_ERROR_MSG",
    "HUB_COMPONENT_THERMODB_REGISTRATION_ERROR_MSG",
    "HUB_COMPONENTS_THERMODB_REGISTRATION_ERROR_MSG",
    "HUB_COMPONENT_MODEL_SOURCE_BUILD_ERROR_MSG",
    "HUB_COMPONENTS_MODEL_SOURCE_BUILD_ERROR_MSG",
    "HubThermoHubBuildError",
    "HubThermoHubCleanError",
    "HubComponentReferenceConfigError",
    "HubComponentReferenceRuleError",
    "HubComponentThermoDBRegistrationError",
    "HubComponentsThermoDBRegistrationError",
    "HubComponentModelSourceBuildError",
    "HubComponentsModelSourceBuildError",

    # API exceptions
    "APIError",
    "APICreationError",
    "InvalidMCPTypeError",
    "InvalidMCPListItemError",
    "MCPAdditionError",
    "API_CREATION_ERROR_MSG",
    "INVALID_MCP_TYPE_ERROR_MSG",
    "INVALID_MCP_LIST_ITEM_ERROR_MSG",
    "MCP_ADDITION_ERROR_MSG",

    # PTF exceptions
    "PTFError",
    "PTFCalculationError",
    "PTFInitializationError",
    "PTFModelSourceError",
    "PTFComponentError",
    "PTFFeedSpecificationError",
    "PTFSolverError",
    "PTF_CALCULATION_ERROR_MSG",
    "PTF_INITIALIZATION_ERROR_MSG",
    "PTF_MODEL_SOURCE_ERROR_MSG",
    "PTF_COMPONENT_ERROR_MSG",
    "PTF_FEED_SPECIFICATION_ERROR_MSG",
    "PTF_SOLVER_ERROR_MSG",

    # PTM exceptions
    "PTMError",
    "PTMCalculationError",
    "PTMInitializationError",
    "PTMModelSourceError",
    "PTMComponentError",
    "PTMFeedSpecificationError",
    "PTMSolverError",
    "PTMReferenceError",
    "PTMFugacityError",
    "PTMRootsAnalysisError",
    "PTM_CALCULATION_ERROR_MSG",
    "PTM_INITIALIZATION_ERROR_MSG",
    "PTM_MODEL_SOURCE_ERROR_MSG",
    "PTM_COMPONENT_ERROR_MSG",
    "PTM_FEED_SPECIFICATION_ERROR_MSG",
    "PTM_SOLVER_ERROR_MSG",
    "PTM_REFERENCE_ERROR_MSG",
    "PTM_FUGACITY_ERROR_MSG",
    "PTM_ROOTS_ANALYSIS_ERROR_MSG",
]
